language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TESTS=ci
  - TESTS=its
    SQ_VERSION=DEV
  - TESTS=its
    SQ_VERSION=LATEST_RELEASE
  - TESTS=its
    SQ_VERSION=LTS

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
