language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TESTS=CI
  - TESTS=IT-DEV
  - TESTS=IT-LTS_OR_OLDEST_COMPATIBLE

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
