language: java
sudo: false

jdk:
  - oraclejdk8

install: true
mvn verify -B -e -V
env:
  - TARGET=CI
  
matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis and integration tests
    - $HOME/.sonar

notifications:
  email: false
