language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TARGET=CI
  
matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis and integration tests
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "d413ZIqyY3Lv7si73C5ROqN8wfNRDhNW1Y56EXutdB3zA1f/Ty3SRVc0viEG93KKPwI6nc8geWHoAEjhT5xnEXz7LE5mVEitogcAS51bsbecwCChgR0m8Dfpf8uou+0nsZak2xynr9c+AakND2nog6SqrMbez+DdjjUuvaKCxwU="
