language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TARGET=CI
  - TARGET=IT SQ_VERSION=DEV
  - TARGET=IT SQ_VERSION=LATEST_RELEASE
  - TARGET=IT SQ_VERSION=LTS

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis and integration tests
    - $HOME/.sonar

notifications:
  email: false
